### ISSUE TITLE
Cheat Menu Crashes Modloader64

### ISSUE THREAD

**Issue by KibaOfficial** [JerryWester/ML64OoTCheatMenu#8]
Hey there,
i tryed to use the Cheat Menu in my Modloader64 (newest version) and it crashed

here is the error report:
```
[1m[31m[2022-10-29T12:59:56.180] [ERROR] M64p - [0mNo auto-config found for joystick named 'Xbox One S Controller' in InputAutoConfig.ini
[1m[31m[2022-10-29T12:59:56.467] [ERROR] M64p - [0mNo auto-config found for joystick named 'Xbox One S Controller' in InputAutoConfig.ini
Error: Cannot find module 'MajorasMask/API/MMAPI'
Require stack:
- G:\Games\Modloader64\ModLoader\ModLoader64_temp_b5PipI\cheatmenu\cheatmenuClient.js
- G:\Games\Modloader64\ModLoader\ModLoader64_temp_b5PipI\cheatmenu\cheatmenu.js
- G:\Games\Modloader64\ModLoader\src\modloader\pluginLoader.mls
- G:\Games\Modloader64\ModLoader\src\modloader\modloader64.mls
- G:\Games\Modloader64\ModLoader\src\loader.mls
- G:\Games\Modloader64\ModLoader\src\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function.Module._resolveFilename (G:\Games\Modloader64\ModLoader\node_modules\module-alias\index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (G:\Games\Modloader64\src\cheatmenu\cheatmenuClient.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)

```

**Comment by JerryWester** [comment]
You're missing the Majora's Mask core. Get it from the ModLoader64 Discord or the Hylian Modding GitHub

**Comment by KibaOfficial** [comment]
> You're missing the Majora's Mask core. Get it from the ModLoader64 Discord or the Hylian Modding GitHub

do you mean the MajorasMaskOnline.pak?

**Comment by JerryWester** [comment]
> > You're missing the Majora's Mask core. Get it from the ModLoader64 Discord or the Hylian Modding GitHub
> 
> do you mean the MajorasMaskOnline.pak?

No, I mean [the core](https://github.com/hylian-modding/Core-MajorasMask/releases/)

**Comment by lulujika** [comment]
its still crash is there a oot core?
